//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodiRemote.Wp81.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KodiRemote.Wp81.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Center Remote.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDIA CENTER REMOTE.
        /// </summary>
        public static string ApplicationTitle_Cap {
            get {
                return ResourceManager.GetString("ApplicationTitle_Cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIONS.
        /// </summary>
        public static string Global_Actions {
            get {
                return ResourceManager.GetString("Global_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Playlist.
        /// </summary>
        public static string Global_Add_To_Playlist {
            get {
                return ResourceManager.GetString("Global_Add_To_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Global_Album_Label {
            get {
                return ResourceManager.GetString("Global_Album_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string Global_Albums {
            get {
                return ResourceManager.GetString("Global_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast.
        /// </summary>
        public static string Global_Cast {
            get {
                return ResourceManager.GetString("Global_Cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAST.
        /// </summary>
        public static string Global_Cast_Capital {
            get {
                return ResourceManager.GetString("Global_Cast_Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Global_Download {
            get {
                return ResourceManager.GetString("Global_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Global_Downloads {
            get {
                return ResourceManager.GetString("Global_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is being downloaded to your phone..
        /// </summary>
        public static string Global_Downloads_Started_Format {
            get {
                return ResourceManager.GetString("Global_Downloads_Started_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened..
        /// </summary>
        public static string Global_Error_Message {
            get {
                return ResourceManager.GetString("Global_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Global_Genre {
            get {
                return ResourceManager.GetString("Global_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Global_Minutes {
            get {
                return ResourceManager.GetString("Global_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parental Rating.
        /// </summary>
        public static string Global_Parental_Rating {
            get {
                return ResourceManager.GetString("Global_Parental_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Global_Play {
            get {
                return ResourceManager.GetString("Global_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Global_Rating {
            get {
                return ResourceManager.GetString("Global_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        public static string Global_Remote {
            get {
                return ResourceManager.GetString("Global_Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote control.
        /// </summary>
        public static string Global_Remote_Control {
            get {
                return ResourceManager.GetString("Global_Remote_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        public static string Global_Runtime {
            get {
                return ResourceManager.GetString("Global_Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See on IMDB.
        /// </summary>
        public static string Global_See_On_Imdb {
            get {
                return ResourceManager.GetString("Global_See_On_Imdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        public static string Global_Songs {
            get {
                return ResourceManager.GetString("Global_Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SONGS.
        /// </summary>
        public static string Global_Songs_Capital {
            get {
                return ResourceManager.GetString("Global_Songs_Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio.
        /// </summary>
        public static string Global_Studio {
            get {
                return ResourceManager.GetString("Global_Studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMMARY.
        /// </summary>
        public static string Global_Summary {
            get {
                return ResourceManager.GetString("Global_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Global_Year {
            get {
                return ResourceManager.GetString("Global_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Main_Page_Tile_About {
            get {
                return ResourceManager.GetString("Main_Page_Tile_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addons.
        /// </summary>
        public static string Main_Page_Tile_Addons {
            get {
                return ResourceManager.GetString("Main_Page_Tile_Addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Main_Page_Tile_Movies {
            get {
                return ResourceManager.GetString("Main_Page_Tile_Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Main_Page_Tile_Music {
            get {
                return ResourceManager.GetString("Main_Page_Tile_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string Main_Page_Tile_Playlists {
            get {
                return ResourceManager.GetString("Main_Page_Tile_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Main_Page_Tile_Settings {
            get {
                return ResourceManager.GetString("Main_Page_Tile_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Shows.
        /// </summary>
        public static string Main_Page_Tile_Tv_Shows {
            get {
                return ResourceManager.GetString("Main_Page_Tile_Tv_Shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback.
        /// </summary>
        public static string Page_About_App_Bar_Feedback {
            get {
                return ResourceManager.GetString("Page_About_App_Bar_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review the application.
        /// </summary>
        public static string Page_About_App_Bar_Review {
            get {
                return ResourceManager.GetString("Page_About_App_Bar_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Page_About_App_Bar_Share {
            get {
                return ResourceManager.GetString("Page_About_App_Bar_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2016 Fabien Lavocat.
        /// </summary>
        public static string Page_About_Copyright {
            get {
                return ResourceManager.GetString("Page_About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Kodi.
        /// </summary>
        public static string Page_About_Get_Kodi {
            get {
                return ResourceManager.GetString("Page_About_Get_Kodi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am using the app Media Center Remote to control Kodi from my Windows Phone..
        /// </summary>
        public static string Page_About_Share_Message {
            get {
                return ResourceManager.GetString("Page_About_Share_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Page_About_Title {
            get {
                return ResourceManager.GetString("Page_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate.
        /// </summary>
        public static string Page_Actions_Hibernate {
            get {
                return ResourceManager.GetString("Page_Actions_Hibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power off System.
        /// </summary>
        public static string Page_Actions_Power_Off {
            get {
                return ResourceManager.GetString("Page_Actions_Power_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        public static string Page_Actions_Reboot {
            get {
                return ResourceManager.GetString("Page_Actions_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        public static string Page_Actions_Suspend {
            get {
                return ResourceManager.GetString("Page_Actions_Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Audio Library.
        /// </summary>
        public static string Page_Actions_Update_Audio_Library {
            get {
                return ResourceManager.GetString("Page_Actions_Update_Audio_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update of the Audio library has been requested. It can take few minutes before you see new items..
        /// </summary>
        public static string Page_Actions_Update_Message_Audio_Message {
            get {
                return ResourceManager.GetString("Page_Actions_Update_Message_Audio_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update of the Video library has been requested. It can take few minutes before you see new items..
        /// </summary>
        public static string Page_Actions_Update_Message_Video_Message {
            get {
                return ResourceManager.GetString("Page_Actions_Update_Message_Video_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Video Library.
        /// </summary>
        public static string Page_Actions_Update_Video_Library {
            get {
                return ResourceManager.GetString("Page_Actions_Update_Video_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Page_Addon_App_Bar_Start {
            get {
                return ResourceManager.GetString("Page_Addon_App_Bar_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Page_Addon_App_Bar_Stop {
            get {
                return ResourceManager.GetString("Page_Addon_App_Bar_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Page_Addon_Author {
            get {
                return ResourceManager.GetString("Page_Addon_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Page_Addon_Description {
            get {
                return ResourceManager.GetString("Page_Addon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclamer.
        /// </summary>
        public static string Page_Addon_Disclamer {
            get {
                return ResourceManager.GetString("Page_Addon_Disclamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Broken?.
        /// </summary>
        public static string Page_Addon_Is_Broken {
            get {
                return ResourceManager.GetString("Page_Addon_Is_Broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Enabled?.
        /// </summary>
        public static string Page_Addon_Is_Enabled {
            get {
                return ResourceManager.GetString("Page_Addon_Is_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addon.
        /// </summary>
        public static string Page_Addon_Title {
            get {
                return ResourceManager.GetString("Page_Addon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Page_Addon_Version {
            get {
                return ResourceManager.GetString("Page_Addon_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addons.
        /// </summary>
        public static string Page_Addons_Title {
            get {
                return ResourceManager.GetString("Page_Addons_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow your phone to vibrate on the remote.
        /// </summary>
        public static string Page_App_Settings_AllowVibrate {
            get {
                return ResourceManager.GetString("Page_App_Settings_AllowVibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to download images of the movies, TV Shows or music albums on your phone?.
        /// </summary>
        public static string Page_App_Settings_Description {
            get {
                return ResourceManager.GetString("Page_App_Settings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Fan Art background.
        /// </summary>
        public static string Page_App_Settings_Download_FanArt {
            get {
                return ResourceManager.GetString("Page_App_Settings_Download_FanArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download thumbnails.
        /// </summary>
        public static string Page_App_Settings_Download_Thumbnails {
            get {
                return ResourceManager.GetString("Page_App_Settings_Download_Thumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Page_App_Settings_Title {
            get {
                return ResourceManager.GetString("Page_App_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to download.
        /// </summary>
        public static string Page_Downloads_Nothing_To_Download {
            get {
                return ResourceManager.GetString("Page_Downloads_Nothing_To_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download is completed.
        /// </summary>
        public static string Page_Downloads_Status_Completed {
            get {
                return ResourceManager.GetString("Page_Downloads_Status_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying the file on your phone.
        /// </summary>
        public static string Page_Downloads_Status_Copying {
            get {
                return ResourceManager.GetString("Page_Downloads_Status_Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download in progress....
        /// </summary>
        public static string Page_Downloads_Status_Downloading {
            get {
                return ResourceManager.GetString("Page_Downloads_Status_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened.
        /// </summary>
        public static string Page_Downloads_Status_Error {
            get {
                return ResourceManager.GetString("Page_Downloads_Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download initialized.
        /// </summary>
        public static string Page_Downloads_Status_Initialized {
            get {
                return ResourceManager.GetString("Page_Downloads_Status_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download paused.
        /// </summary>
        public static string Page_Downloads_Status_Paused {
            get {
                return ResourceManager.GetString("Page_Downloads_Status_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing the temporary file.
        /// </summary>
        public static string Page_Downloads_Status_Removing {
            get {
                return ResourceManager.GetString("Page_Downloads_Status_Removing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer.
        /// </summary>
        public static string Page_Episode_Writer {
            get {
                return ResourceManager.GetString("Page_Episode_Writer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDB.
        /// </summary>
        public static string Page_Episodes_Imdb {
            get {
                return ResourceManager.GetString("Page_Episodes_Imdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEASONS.
        /// </summary>
        public static string Page_Episodes_Seasons {
            get {
                return ResourceManager.GetString("Page_Episodes_Seasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no movie available in your library..
        /// </summary>
        public static string Page_Movies_Message_No_Movie {
            get {
                return ResourceManager.GetString("Page_Movies_Message_No_Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directed by.
        /// </summary>
        public static string Page_Movies_Movie_Director {
            get {
                return ResourceManager.GetString("Page_Movies_Movie_Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAILER.
        /// </summary>
        public static string Page_Movies_Movie_Trailer {
            get {
                return ResourceManager.GetString("Page_Movies_Movie_Trailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recently added.
        /// </summary>
        public static string Page_Movies_Movies_RecentlyAdded {
            get {
                return ResourceManager.GetString("Page_Movies_Movies_RecentlyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort by title.
        /// </summary>
        public static string Page_Movies_OrderBy_Title {
            get {
                return ResourceManager.GetString("Page_Movies_OrderBy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort by year.
        /// </summary>
        public static string Page_Movies_OrderBy_Year {
            get {
                return ResourceManager.GetString("Page_Movies_OrderBy_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recently added.
        /// </summary>
        public static string Page_Movies_RecentlyAdded_Title {
            get {
                return ResourceManager.GetString("Page_Movies_RecentlyAdded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Page_Movies_Title {
            get {
                return ResourceManager.GetString("Page_Movies_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no music available in your library..
        /// </summary>
        public static string Page_Music_Message_No_Musique {
            get {
                return ResourceManager.GetString("Page_Music_Message_No_Musique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to albums.
        /// </summary>
        public static string Page_Music_Musics_Album {
            get {
                return ResourceManager.GetString("Page_Music_Musics_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artists.
        /// </summary>
        public static string Page_Music_Musics_Artists {
            get {
                return ResourceManager.GetString("Page_Music_Musics_Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genres.
        /// </summary>
        public static string Page_Music_Musics_Genres {
            get {
                return ResourceManager.GetString("Page_Music_Musics_Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Page_Music_Title {
            get {
                return ResourceManager.GetString("Page_Music_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUSIC.
        /// </summary>
        public static string Page_Music_Title_cap {
            get {
                return ResourceManager.GetString("Page_Music_Title_cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Page_Playlists_Clear {
            get {
                return ResourceManager.GetString("Page_Playlists_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your playlists are empty..
        /// </summary>
        public static string Page_Playlists_No_Playlist {
            get {
                return ResourceManager.GetString("Page_Playlists_No_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string Page_Playlists_Title {
            get {
                return ResourceManager.GetString("Page_Playlists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Page_Send_Text_Send {
            get {
                return ResourceManager.GetString("Page_Send_Text_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to send.
        /// </summary>
        public static string Page_Send_Text_Text_To_Send {
            get {
                return ResourceManager.GetString("Page_Send_Text_Text_To_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send text.
        /// </summary>
        public static string Page_Send_Text_Title {
            get {
                return ResourceManager.GetString("Page_Send_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new connection.
        /// </summary>
        public static string Page_Servers_Add {
            get {
                return ResourceManager.GetString("Page_Servers_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Page_Servers_App_Bar_Edit {
            get {
                return ResourceManager.GetString("Page_Servers_App_Bar_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Page_Servers_App_Bar_Remove {
            get {
                return ResourceManager.GetString("Page_Servers_App_Bar_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the selected Kodi connection?.
        /// </summary>
        public static string Page_Servers_App_Bar_Remove_Confirm {
            get {
                return ResourceManager.GetString("Page_Servers_App_Bar_Remove_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have anymore connection. You need to add a new one..
        /// </summary>
        public static string Page_Servers_No_Move_Connection {
            get {
                return ResourceManager.GetString("Page_Servers_No_Move_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KODI SERVERS.
        /// </summary>
        public static string Page_Servers_Title {
            get {
                return ResourceManager.GetString("Page_Servers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wake On Lan.
        /// </summary>
        public static string Page_Servers_Wake_On_Lan {
            get {
                return ResourceManager.GetString("Page_Servers_Wake_On_Lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Page_Settings_Button_Save {
            get {
                return ResourceManager.GetString("Page_Settings_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity test.
        /// </summary>
        public static string Page_Settings_Connectivity_Test {
            get {
                return ResourceManager.GetString("Page_Settings_Connectivity_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Address.
        /// </summary>
        public static string Page_Settings_MAC_Address {
            get {
                return ResourceManager.GetString("Page_Settings_MAC_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. Used for Wake On Lan. Format: 00:00:00:00:00:00.
        /// </summary>
        public static string Page_Settings_MAC_Address_Optional {
            get {
                return ResourceManager.GetString("Page_Settings_MAC_Address_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Page_Settings_Password {
            get {
                return ResourceManager.GetString("Page_Settings_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi Port Number.
        /// </summary>
        public static string Page_Settings_Port_Number {
            get {
                return ResourceManager.GetString("Page_Settings_Port_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi Server Address.
        /// </summary>
        public static string Page_Settings_Server_Address {
            get {
                return ResourceManager.GetString("Page_Settings_Server_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi is not available :(.
        /// </summary>
        public static string Page_Settings_Test_Bad {
            get {
                return ResourceManager.GetString("Page_Settings_Test_Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re good to go!.
        /// </summary>
        public static string Page_Settings_Test_Good {
            get {
                return ResourceManager.GetString("Page_Settings_Test_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings.
        /// </summary>
        public static string Page_Settings_Title {
            get {
                return ResourceManager.GetString("Page_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Page_Settings_Username {
            get {
                return ResourceManager.GetString("Page_Settings_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep watched.
        /// </summary>
        public static string Page_Tv_Shows_Keep_Watched {
            get {
                return ResourceManager.GetString("Page_Tv_Shows_Keep_Watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no TV show available in your library..
        /// </summary>
        public static string Page_Tv_Shows_Message_No_Tv_Show {
            get {
                return ResourceManager.GetString("Page_Tv_Shows_Message_No_Tv_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Watched.
        /// </summary>
        public static string Page_Tv_Shows_Not_Watched {
            get {
                return ResourceManager.GetString("Page_Tv_Shows_Not_Watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Page_Tv_Shows_Refresh {
            get {
                return ResourceManager.GetString("Page_Tv_Shows_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove watched.
        /// </summary>
        public static string Page_Tv_Shows_Remove_Watched {
            get {
                return ResourceManager.GetString("Page_Tv_Shows_Remove_Watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons.
        /// </summary>
        public static string Page_Tv_Shows_Seasons {
            get {
                return ResourceManager.GetString("Page_Tv_Shows_Seasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Shows.
        /// </summary>
        public static string Page_Tv_Shows_Title {
            get {
                return ResourceManager.GetString("Page_Tv_Shows_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} votes.
        /// </summary>
        public static string Page_Tv_Shows_Votes_Format {
            get {
                return ResourceManager.GetString("Page_Tv_Shows_Votes_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched.
        /// </summary>
        public static string Page_Tv_Shows_Watched {
            get {
                return ResourceManager.GetString("Page_Tv_Shows_Watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Kodi Server.
        /// </summary>
        public static string Page_Welcome_Add_Button {
            get {
                return ResourceManager.GetString("Page_Welcome_Add_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string Page_Welcome_Get_Started {
            get {
                return ResourceManager.GetString("Page_Welcome_Get_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before using the application, you must select the Kodi server you want to connect to..
        /// </summary>
        public static string Page_Welcome_Message {
            get {
                return ResourceManager.GetString("Page_Welcome_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
